tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "raggi/ale"
tap "universal-ctags/universal-ctags"
brew "ack"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "python@3.9"
brew "ansible"
brew "ansible-lint"
brew "autoconf"
brew "automake"
brew "libtool"
brew "asdf"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bat"
brew "icu4c"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "eigen"
brew "gmp"
brew "cmark"
brew "direnv"
brew "exa"
brew "fish"
brew "fzf"
brew "jpeg"
brew "openblas"
brew "ghostscript"
brew "gifsicle"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-open"
brew "git-secrets"
brew "gnu-sed"
brew "pinentry"
brew "gnupg"
brew "hivemind"
brew "htmldoc"
brew "imath"
brew "openexr"
brew "imagemagick"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "protobuf"
brew "libphonenumber"
brew "libxmlsec1"
brew "mas"
brew "mdbtools"
brew "optipng"
brew "pinentry-mac"
brew "pipenv"
brew "postgresql"
brew "protobuf-c"
brew "postgis"
brew "proselint"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "starship"
brew "stow"
brew "watchman"
brew "wget"
brew "raggi/ale/openssl-osx-ca"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "clipy"
cask "firefox"
cask "font-hack"
cask "font-hack-nerd-font"
cask "gotomeeting"
cask "macvim"
cask "private-internet-access"
cask "qlcommonmark"
cask "qlimagesize"
cask "qlprettypatch"
cask "qlstephen"
cask "rectangle"
cask "sketchup"
cask "transmission"
cask "vlc"
mas "1Password 7", id: 1333542190
mas "AdGuard for Safari", id: 1440147259
mas "Day One", id: 1055511498
mas "Free Ruler", id: 1483172210
mas "Irvue", id: 1039633667
mas "Pins", id: 1547106997
mas "Pixelmator", id: 407963104
mas "Reeder", id: 1529448980
mas "Slack", id: 803453959
mas "Things", id: 904280696
mas "Xcode", id: 497799835
