tap "beeftornado/rmtree"
tap "cooklang/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "sqlite"
brew "ansible"
brew "ansible-lint"
brew "imath"
brew "jpeg", link: true
brew "libpng"
brew "libtiff"
brew "openexr"
brew "webp"
brew "autoconf"
brew "automake"
brew "gmp"
brew "libtool"
brew "asdf"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bash"
brew "bat"
brew "icu4c"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "cmark"
brew "exa"
brew "fish"
brew "fzf"
brew "little-cms2"
brew "openjpeg"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-secrets"
brew "gnu-sed"
brew "htmldoc"
brew "libffi"
brew "python@3.9"
brew "shared-mime-info"
brew "imagemagick"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "mas"
brew "openssh"
brew "openssl@3"
brew "optipng"
brew "pipenv"
brew "poetry"
brew "postgresql@14"
brew "proselint"
brew "r"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "starship"
brew "stow"
brew "universal-ctags"
brew "watchman"
brew "wget"
brew "yq"
brew "zlib"
brew "cooklang/tap/cook"
cask "1password"
cask "1password-cli"
cask "chromium"
cask "clipy"
cask "firefox"
cask "font-hack-nerd-font"
cask "freecad"
cask "google-chrome"
cask "gotomeeting"
cask "mactex-no-gui"
cask "macvim"
cask "qlcommonmark"
cask "qlimagesize"
cask "qlprettypatch"
cask "qlstephen"
cask "rectangle"
cask "rstudio"
cask "transmission"
cask "vlc"
mas "1Password for Safari", id: 1569813296
mas "AdGuard for Safari", id: 1440147259
mas "Free Ruler", id: 1483172210
mas "Pins", id: 1547106997
mas "Pixelmator", id: 407963104
mas "Reeder", id: 1529448980
mas "Things", id: 904280696
mas "Tomito", id: 1526042938
mas "Xcode", id: 497799835
