tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
brew "imath"
brew "libpng"
brew "libtiff"
brew "little-cms2"
brew "openexr"
brew "webp"
brew "autoconf"
brew "automake"
brew "gmp"
brew "libtool"
brew "libyaml"
brew "readline"
brew "asdf"
brew "sqlite"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bash"
brew "oniguruma"
brew "bat"
brew "icu4c"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "cmark"
brew "composer"
brew "exa"
brew "openjpeg"
brew "fish"
brew "fzf"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-secrets"
brew "gnu-sed"
brew "htmldoc"
brew "shared-mime-info"
brew "libffi"
brew "python@3.9"
brew "imagemagick"
brew "jpeg"
brew "jpegoptim"
brew "jq"
brew "libxml2"
brew "libxslt"
brew "mas"
brew "zlib"
brew "mysql"
brew "optipng"
brew "parallel"
brew "pipenv"
brew "poetry"
brew "postgresql@15", link: true
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "starship"
brew "stow"
brew "terminal-notifier"
brew "universal-ctags"
brew "watchman"
brew "wget"
brew "yq"
cask "clipy"
cask "firefox"
cask "font-hack-nerd-font"
cask "freecad"
cask "google-chrome"
cask "gotomeeting"
cask "macdown"
cask "macvim"
cask "qlcommonmark"
cask "qlimagesize"
cask "qlprettypatch"
cask "qlstephen"
cask "rectangle"
cask "tor-browser"
cask "transmission"
cask "vlc"
mas "AdGuard for Safari", id: 1440147259
mas "Free Ruler", id: 1483172210
mas "Mela", id: 1568924476
mas "Omnivore", id: 1564031042
mas "Pixelmator", id: 407963104
mas "Reeder", id: 1529448980
mas "Things", id: 904280696
mas "Tomito", id: 1526042938
mas "Xcode", id: 497799835
