[aws]
disabled = true

[battery]
disabled = true

[character]
error_symbol = "[✖](bold red)"

[directory]
truncate_to_repo = false

[golang]
disabled = true

[kotlin]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[swift]
disabled = true
