#!/bin/sh

# From tpope's ctags setup: https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e

trap 'rm -f "$$.tags"' EXIT

git ls-files | \
  ctags --tag-relative=yes -L - -f"$$.tags" --languages=-javascript,sql
mv "$$.tags" "tags"
