#!/bin/bash

# Grabs AWS credentials from 1Password and formats them for use in
# `~/.aws/config` `credential_process` param.
#
# Arguments:
#   - Item (required): the name or UUID of the item in 1Password
#   - ID Field (optional, default "access_key_id"): The field that contains the
#     AWS Access Key ID
#   - Secret Field (optional, default "secret_access_key"): The field that
#     contains the AWS Secret Access Key

set -euo pipefail
IFS=$'\n\t'

if [ $# -lt 1 ]; then
  echo "Usage: $(basename "$0") [op_item]"
  exit 1
fi

id_field=${2:-'access_key_id'}
secret_field=${3:-'secret_access_key'}

op item get "$1" --cache --format=json --fields="label=$id_field,label=$secret_field" \
  | jq '{Version: 1, AccessKeyId: .[0].value, SecretAccessKey: .[1].value}'
