#!/bin/bash

# Grabs AWS credentials from 1Password and formats them for use in
# `~/.aws/config` `credential_process` param.

set -euo pipefail
IFS=$'\n\t'

if [ $# -ne 1 ]; then
    echo "Usage: $0 [op_item]"
  exit 1
fi

op item get "$1" --cache --format=json \
  | jq '.fields | map({(.label):.value}) | add | {Version:1, AccessKeyId:.username, SecretAccessKey:.credential}'
