#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

ipod_path="${IPOD_PATH:-/Volumes/IPOD}"

if [ -z "$ipod_path" ]; then
  echo 'You must specify an IPOD_PATH' >&2
  exit 1
fi

if [ ! -d "$ipod_path" ]; then
  echo "Directory $ipod_path does not exist. Is your iPod plugged in?" >&2
  exit 1
fi

rsync \
  --delete \
  --exclude-from="$HOME"/.rsync_exclude \
  --iconv=utf-8-mac,utf-8 \
  --modify-window=1 \
  --progress \
  --recursive \
  --times \
  --update \
  --verbose \
  "$HOME"/Music/Music/ \
  "$ipod_path"/Music/
