#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Store the current directory and switch to the project root.
dir=$(pwd)
cd "$(dirname "$(greadlink -f "$0")")/../.." || exit 1

STASH_COUNT=$(git stash list | wc -l)

trap cleanup INT TERM EXIT
cleanup() {
  if [ "$STASH_COUNT" != "$(git stash list | wc -l)" ]; then
    git stash pop --quiet
  fi
  if [ "$(pwd)" != "$dir" ]; then
    echo "*** Returning you to $dir from $(pwd)"
    cd "$dir" || exit 1
  fi
  exit 0
}

commit_if_changed() {
  if [ "$(git status --porcelain | wc -l)" -eq 0 ]; then return; fi
  git add .
  msg=${1:-"Updating submodules, vim plugins, and/or brew list."}
  git ci -m "$msg"
}

# If there are changes, stash them.
git stash --quiet

git pull origin master

# Apps from the App Store.
if command -v mas > /dev/null; then
  mas upgrade
fi

# homebrew and casks.
if command -v brew > /dev/null; then
  brew update
  HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade
  HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew cask upgrade --greedy
  brew cleanup
  brew bundle --global --force --no-restart dump
  "$HOMEBREW_PREFIX/opt/fzf/install" --no-bash --no-fish --all
  commit_if_changed "brew: Updating brews"
fi

# git submodules.
git submodule foreach git pull
commit_if_changed "Updating git submodules"

# zsh plugins.
zsh -c "source \"$ZPLUG_HOME/init.zsh\" && source \"$HOME/.zsh/zplug.zsh\" && zplug update"
commit_if_changed "zsh: Updating plugins"

# vim plugins
[ -f "$HOME/.minpac_update.tmp" ] && rm "$HOME/.minpac_update.tmp" > /dev/null
vim -f -c "redir > $HOME/.minpac_update.tmp | call PackInit() | call minpac#update('', {'do': 'quit'})"
command cat "$HOME/.minpac_update.tmp"
rm "$HOME/.minpac_update.tmp" > /dev/null
commit_if_changed "vim: Updating plugins"

# asdf plugins
asdf plugin-update --all
commit_if_changed "asdf: Updating plugins"

# Finally, push to remote if we need to.
if [ "$(git rev-parse '@{u}')" != "$(git rev-parse @)" ]; then
  git push origin master
else
  echo "Nothing updated, no push needed."
fi
