#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Process options.
NO_COMMIT=0
NO_PUSH=0
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "update"
      echo " "
      echo "options:"
      echo "-h, --help                show brief help"
      echo "-c, --no-commit           don't commit changes (implies --no-push)"
      echo "-p, --no-push             don't push commits"
      exit 0
      ;;
    -c|--no-commit)
      export NO_COMMIT=1
      export NO_PUSH=1
      shift
      ;;
    -p|--no-push)
      export NO_PUSH=1
      shift
      ;;
    *)
      break
      ;;
  esac
done

# Store the current directory and switch to the project root.
dir=$(pwd)
cd "$(dirname "$(greadlink -f "$0")")/../.." || exit 1

STASH_COUNT=$(git stash list | wc -l)

trap cleanup INT TERM EXIT
cleanup() {
  if [ "$STASH_COUNT" != "$(git stash list | wc -l)" ]; then
    git stash pop --quiet
  fi
  if [ "$(pwd)" != "$dir" ]; then
    echo "*** Returning you to $dir from $(pwd)"
    cd "$dir" || exit 1
  fi
  exit 0
}

commit_if_changed() {
  if [ $NO_COMMIT -eq 1 ]; then return; fi
  if [ "$(git status --porcelain | wc -l)" -eq 0 ]; then return; fi
  git add .
  msg=${1:-"Updating submodules, vim plugins, and/or brew list."}
  git ci -m "$msg"
}

# If there are changes, stash them.
git stash --quiet

git pull origin master

# Apps from the App Store.
if command -v mas > /dev/null; then
  mas upgrade
fi

# homebrew and casks.
if command -v brew > /dev/null; then
  brew update
  HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade --ignore-pinned --greedy
  HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew cleanup
  HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew bundle --global --force --no-restart dump
  "$HOMEBREW_PREFIX/opt/fzf/install" --no-bash --no-zsh --all
  commit_if_changed "brew: Updating brews"
fi

# git submodules.
git submodule foreach git pull
commit_if_changed "Updating git submodules"

# vim plugins
mvim -f -c "call PackagerInit() | call packager#update({'on_finish': ':w! >>/dev/tty | quitall'})"
commit_if_changed "vim: Updating plugins"

# asdf plugins
asdf plugin update --all
commit_if_changed "asdf: Updating plugins"

# Finally, push to remote if we need to.
if [ $NO_PUSH -eq 1 ]; then
  echo "Skipping git push"
elif [ "$(git rev-parse '@{u}')" != "$(git rev-parse @)" ]; then
  git push origin master
else
  echo "Nothing updated, no push needed."
fi
