" XDG stuff
" https://blog.joren.ga/configuring/vim-xdg
if empty($MYVIMRC) | let $MYVIMRC = expand('%:p') | endif
if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME."/.cache"       | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config"      | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME   = $HOME."/.local/share" | endif
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set runtimepath+=$XDG_DATA_HOME/vim
set packpath^=$XDG_DATA_HOME/vim
call mkdir($XDG_DATA_HOME."/vim/spell", 'p', 0700)
set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p', 0700)
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p', 0700)
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p', 0700)
set viewdir=$XDG_CACHE_HOME/vim/view     | call mkdir(&viewdir,   'p', 0700)

if !has('nvim') " Neovim has its own location which already complies with XDG specification
  set viminfofile=$XDG_CACHE_HOME/vim/viminfo
endif

" Fix vim defaults
set nocompatible
set lazyredraw
set ttyfast
set nostartofline           " Make j/k respect the columns (after all, this is not a freaking typewriter)
set modeline                " Respect modeline of the file (the famous "vi:noai:sw=3 ts=6" on the beginning of the files)
set hidden                  " Avoid asking to save before hiding

" Fixes funny things when we use non-POSIX-compliant shells, like fish.
set shell=/bin/sh

filetype on
filetype off

" Load fzf from homebrew
" This needs to happen before we load plugins so that the `fzf.vim` plugin can
" find it.
let &rtp .= ',' . $HOMEBREW_PREFIX . '/opt/fzf'

" Plugins
runtime! plugins.vim

" Basic UI
set visualbell
set shortmess=atIWs
set title
set numberwidth=1
set number
set relativenumber
set report=2
set showmode

if has('title') && (has('gui_running') || &title)
  set titlestring=
  set titlestring+=%t " file name
  set titlestring+=%(\ %h%m%r%w%) " flags
endif

" Command-mode completion
set wildignore=*.o,*.obj,*.pyc,*.swc,*.DS_STORE,*.bkp
set wildmode=list:longest

" Clipboard
set clipboard=unnamed

" Soft/Hard Wrapping
set wrap
set textwidth=79
set formatoptions=qrn1

" History and backup
set viminfo='10,:20,\"100,%,n~/.viminfo
set nobackup
set nowritebackup
set noswapfile

" Undo
if (v:version > 703)
  set undofile
  set undoreload=10000
endif

" Format
set formatprg=par
