#!/usr/bin/env php

<?php

/**
 * Returns instructions on how to use this script.
 *
 * @return string
 */
function usage() {
  return <<<USAGE
DNS switch notifier.

Usage:
dns_switch_notifier -c [current_ip] -d [domain] -e [comma-separated emails] -t[time between pings]


USAGE;
}

// Get the arguments from the command line.
$arguments = getopt('c:d:e::t::');

// The "c" and "d" arguments are required.
if (isset($arguments['c'], $arguments['d'])) {
  $current_ip = $arguments['c'];
  $domain = $arguments['d'];
  echo "Checking {$domain} for something other than {$current_ip}\n\n";
}
else {
  echo usage();
  exit(1);
}

// Set the frequency of pings.
$frequency = isset($arguments['t']) ? (int) $arguments['t'] : 300;

$command = escapeshellcmd('ping -c 1 ' . $domain);

// Check the IP address until it differs from the one given.
do {
  echo 'Pinging...';
  $output = shell_exec($command);
  echo sprintf("done. Next ping at %s.\n", date('g:i:sa', time() + $frequency));
  sleep($frequency);
}
while (strpos($output, $current_ip) !== FALSE);

// Send emails.
if (!empty($arguments['e'])) {
  foreach (explode(',', $arguments['e']) as $email) {
    mail($mail, 'DNS switched', 'Hi. This is your friendly DNS switch notified script. Just wanted to let you know that ' . $domain . ' is switched.');
  }
}

exit;
